services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
    networks:
      - tunnel-network
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel-network
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}

networks:
  tunnel-network: